var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import { createGlobalStyle } from 'styled-components';
import { fonts } from './styled';
var GlobalStyles = createGlobalStyle(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    * {\n        margin: 0;\n        padding: 0;\n        box-sizing: border-box;\n    }\n\n    html {\n        font-size: 16px;\n        -webkit-text-size-adjust: 100%;\n        -ms-text-size-adjust: 100%;\n    }\n\n    html, body, #root {\n        height: 100%;\n        margin: 0;\n    }\n\n    body {\n        font-family: ", ";\n        font-size: 16px;\n        line-height: 1.5;\n        -webkit-font-smoothing: antialiased;\n        -moz-osx-font-smoothing: grayscale;\n        text-rendering: optimizeLegibility;\n        text-size-adjust: none;\n        -webkit-text-size-adjust: none;\n        -moz-text-size-adjust: none;\n        -ms-text-size-adjust: none;\n    }\n\n    h1, h2, h3, h4, h5, h6, p, ul, ol, li, figure, figcaption, blockquote, dl, dd {\n        margin: 0;\n        padding: 0;\n    }\n    img {\n        max-width: 100%;\n        height: auto;\n        display: block;\n    }\n"], ["\n    * {\n        margin: 0;\n        padding: 0;\n        box-sizing: border-box;\n    }\n\n    html {\n        font-size: 16px;\n        -webkit-text-size-adjust: 100%;\n        -ms-text-size-adjust: 100%;\n    }\n\n    html, body, #root {\n        height: 100%;\n        margin: 0;\n    }\n\n    body {\n        font-family: ", ";\n        font-size: 16px;\n        line-height: 1.5;\n        -webkit-font-smoothing: antialiased;\n        -moz-osx-font-smoothing: grayscale;\n        text-rendering: optimizeLegibility;\n        text-size-adjust: none;\n        -webkit-text-size-adjust: none;\n        -moz-text-size-adjust: none;\n        -ms-text-size-adjust: none;\n    }\n\n    h1, h2, h3, h4, h5, h6, p, ul, ol, li, figure, figcaption, blockquote, dl, dd {\n        margin: 0;\n        padding: 0;\n    }\n    img {\n        max-width: 100%;\n        height: auto;\n        display: block;\n    }\n"])), fonts.primary);
export default GlobalStyles;
var templateObject_1;
